const std = @import("std");
const log = @import("./log.zig");
const util = @import("./util.zig");

pub const Errors = error {
    FailedToWatchFile,
    InvalidOs,
    ForkFailed,
    StdHandleCloseFailed,
    SetSidFailed,
    MissingCwd,
    CommandFailed,
    InternalLoggingFailed,

    MainDirNotFound,
    MainDirFailedCreate,

    PathNotFound,
    TasksFileMissingOrCorrupt,

    TasksDirNotFound,
    TasksDirFailedCreate,

    StartupFileFailedCreate,
    StartupFileFailedRead,
    StartupFileFailedWrite,
    StartupFileNotExists,
    StartupFileEmpty,

    TasksIdsFileFailedCreate,
    TasksIdsFileFailedRead,
    TasksIdsFileFailedWrite,
    TasksIdsFileNotExists,

    TasksNamespacesFileNotExists,
    TaskFileFailedWrite,
    MissingHomeDirectory,
    TaskFileFailedCreate,
    TaskNotExists,
    TaskNotRunning,
    TaskAlreadyRunning,
    NoArgs,
    ParsingCommandArgsFailed,
    InvalidOption,
    MissingArgument,
    MissingArgumentValue,
    InvalidArgument,
    CorruptedTask,
    TaskLogsFailedToRead,
    FailedToSetWindowCols,
    TasksNamespacesFileFailedRead,
    TasksNamespacesFileFailedCreate,
    TasksNamespacesFileFailedDelete,
    NamespaceNotExists,

    FailedToGetProcessStats,
    FailedToGetProcessState,
    FailedToGetProcesses,
    FailedToGetProcessChildren,
    FailedToGetProcess,
    FailedToGetCpuStats,
    FailedToSaveProcesses,
    FailedToReadTaskPid,
    FailedToGetProcessSid,
    FailedToGetProcessPpid,
    CommandTooLarge,

    FailedToSaveStats,
    FailedToGetTaskStats,
    FailedAppendTableRow,
    FailedToGetProcessMemory,
    FailedToGetProcessRuntime,
    FailedToGetCpuUsage,
    FailedToSetCpuUsage,
    FailedToGetProcessComm,
    FailedToGetProcessName,
    FailedToGetProcessStarttime,
    FailedToDeleteTask,

    FailedToSetProcessStatus,

    ProcessNotExists,

    FailedToPrintTable,
    FailedToKillAllProcesses,
    FailedToKillProcess,

    ProcessFileFailedCreate,
    ProcessFileNotFound,

    CpuLimitValueInvalid,
    CpuLimitValueMissing,
    MemoryLimitValueMissing,
    MemoryLimitValueInvalid,
    NamespaceValueMissing,
    NamespaceValueInvalid,

    FailedSetProcessFileCache,
    FailedSetTaskCache,

    InvalidShell,
    UnkownItemInTaskDir,
    UnkownItemInTasksDir,
    NamespaceValueCantBeAll,
    FailedToEditNamespace,
    SpawnExeNotFound,
    FileFailedValidation,
    FailedToCloseFiles,
    InvalidFile,
    InternalUtilError,

    MainFileFailedWrite,
    MainFileFailedRead,

    TaskFileFailedRead,
    MissingTaskId,
    OnlyOneTaskId,
    CommandNotExists,

    FailedToGetAllProcesses,
    FailedToGetProcDir,
    FailedToGetRelatedProcs,

    DebugLogFileFailedWrite,
    DebugLogFileFailedOpen,

    TaskFileNotFound,
    FailedToFilterDupeProcesses,

    FailedToGetRootStats,

    InvalidFileType,
    FailedToGetSystemUptime,

    FailedToGetEnvs,
    FailedToGetLoadavg,
    CorruptTaskIdEnvVariable,
    FailedToGetJob,

    FailedToGetStartupDetails,
    FailedToSetStartupDetails,

    FailedToSpawnThread,
    FailedToSignalLogger,

    WindowsLogWatcherAlreadyRunning,

    // TESTING ERRORS
    TestFunctionCalled,
    TestExpectFailed,
};

pub fn verbose_error(og_err: anytype, mult_err: Errors) Errors {
    if (log.debug) {
        log.printdebug("Error: {any}", .{og_err})
            catch |err| std.debug.print("Error printing debug {any}\n", .{err});
    }
    return mult_err;
}

pub fn get_error_msg(e_type: Errors) Errors![]const u8 {
    return switch (e_type) {
        error.WindowsLogWatcherAlreadyRunning => "There is already a log watcher on this task running.",
        error.FailedToSignalLogger => "Failed to signal the log watcher.",
        error.FailedToWatchFile => "Failed to watch file.",
        error.FailedToSpawnThread => "Failed to spawn thread for monitoring or watching logs.",
        error.FailedToSetStartupDetails => "Failed to set startup details.",
        error.FailedToGetStartupDetails => "Failed to get startup details.",
        error.FailedToGetJob => "Failed to get group of processes.",
        error.CorruptTaskIdEnvVariable => "MULTASK_TASK_ID env variable's value is corrupted.",
        error.FailedToGetLoadavg => "Failed to get the most recent process from /proc/loadavg.",
        error.FailedToGetEnvs => "Failed to get OS envs.",
        error.InvalidOs => "Invalid OS. Only Macos, Linux and Windows supported right now.",
        error.FailedToGetProcessPpid => "Failed to get process parent id.",
        error.FailedToGetProcessSid => "Failed to get process sid.",
        error.FailedToGetSystemUptime => "Failed to get system uptime.",
        error.InvalidFileType => "Invalid file type.",
        error.FailedToGetRootStats => "Failed to get the computer's stats.",
        error.FailedToFilterDupeProcesses => "Could not get unique processes.",
        error.ProcessFileNotFound => "Process file not found.",
        error.TaskFileNotFound => "Task file not found.",
        error.DebugLogFileFailedOpen => "Failed to open debug log file.",
        error.DebugLogFileFailedWrite => "Failed to write to debug log file.",
        error.FailedToGetRelatedProcs => "Failed to get /proc dir.",
        error.FailedToGetProcDir => "Failed to get /proc dir.",
        error.FailedToGetAllProcesses => "Failed to get all processes.",
        error.CommandNotExists => "Command is missing.",
        error.MissingTaskId => "Missing task id.",
        error.OnlyOneTaskId => "Only one task id allowed.",
        error.TaskFileFailedRead => "Failed to read task file.",
        error.MainFileFailedRead => "Failed to read main file.",
        error.MainFileFailedWrite => "Failed to save main file.",
        error.InternalUtilError => "Internal utility function failed.",
        error.InvalidFile => "Invalid file.",
        error.FailedToCloseFiles => "File failed validation.",
        error.FileFailedValidation => "File failed validation.",
        error.SpawnExeNotFound => "Multask spawn executable not found.",
        error.FailedToEditNamespace => "Failed to edit namespace.",
        error.UnkownItemInTaskDir => "Unknown file/directory in task directory.",
        error.UnkownItemInTasksDir => "Unknown file/directory in tasks directory.",
        error.InvalidShell => "Shell is not recognised. Supported shells are zsh and bash at the moment.",
        error.FailedSetProcessFileCache => "Failed to set process file cache.",
        error.FailedSetTaskCache => "Failed to set task file cache.",
        error.ProcessFileFailedCreate => "Failed to create processes file.",
        error.FailedToKillProcess => "Failed to kill process.",
        error.FailedToKillAllProcesses => "Failed to kill all processes.",
        error.FailedToPrintTable => "Failed to print table.",
        error.ProcessNotExists => "Process does not exist.",
        error.FailedToSetProcessStatus => "Failed to set process status.",
        error.FailedToDeleteTask => "Failed to delete task.",
        error.FailedToGetProcessStarttime => "Failed to get process start time.",
        error.FailedToGetProcessName => "Failed to get process name.",
        error.FailedToGetProcessComm => "Failed to get process executable.",
        error.FailedToSetCpuUsage => "Failed to set process cpu usage.",
        error.FailedToGetCpuUsage => "Failed to get process cpu usage.",
        error.FailedToGetProcessRuntime => "Failed to get process runtime.",
        error.FailedToGetProcessMemory => "Failed to get process memory.",
        error.FailedAppendTableRow => "Failed to add table row.",
        error.FailedToGetTaskStats => "Failed to get task stats.",
        error.FailedToSaveStats => "Failed to save task stats.",
        error.CommandTooLarge => "Command is too large.",
        error.FailedToReadTaskPid => "Failed to read task's pid.",
        error.FailedToSaveProcesses => "Failed to save processes.",
        error.FailedToGetCpuStats => "Failed to get CPU stats.",
        error.FailedToGetProcess => "Failed to find process.",
        error.FailedToGetProcessChildren => "Failed to get process children.",
        error.FailedToGetProcesses => "Failed to get processes.",
        error.FailedToGetProcessState => "Failed to get state of process.",
        error.FailedToGetProcessStats => "Failed to get stats of process.",
        error.FailedToSetWindowCols => "Failed to find size of window.",
        error.TaskLogsFailedToRead => "Failed to read task's logs.",
        error.TasksDirNotFound => "Tasks directory not found.",
        error.PathNotFound => "Could not find specified path.",
        error.ForkFailed => "Failed to create a subshell. Maybe this is a terminal I don't recognise?",
        error.StdHandleCloseFailed => "Failed to close stdout/err handles.",
        error.SetSidFailed => "Failed to set the sid of the subshell.",
        error.MissingCwd => "Missing current working working directory.",
        error.CommandFailed => "Command failed to execute.",
        error.MainDirNotFound => "Main directory doesn't exist.",
        error.TasksFileMissingOrCorrupt => "Tasks file is missing or corrupt.",

        error.StartupFileEmpty => "Startup file is empty. Please run mlt health",
        error.StartupFileFailedCreate => "Failed to create startup file.",
        error.StartupFileFailedRead => "Failed to read startup file.",
        error.StartupFileFailedWrite => "Failed to write to startup file.",
        error.StartupFileNotExists => "Startup file does not exist.",

        error.TasksIdsFileFailedCreate => "Failed to create task ids file.",
        error.TasksIdsFileFailedRead => "Failed to read task ids file.",
        error.TasksIdsFileFailedWrite => "Failed to write to task ids file.",
        error.TasksIdsFileNotExists => "Task ids file does not exist.",
        error.TasksNamespacesFileNotExists => "Task namespaces file does not exist.",
        error.TasksNamespacesFileFailedCreate => "Failed to create task namespaces file.",
        error.TasksNamespacesFileFailedRead => "Failed to read task namespaces file.",
        error.TasksNamespacesFileFailedDelete => "Failed to delete task namespaces file.",
        error.TaskFileFailedWrite => "Task output failed to write.",
        error.MissingHomeDirectory => "Missing home directory.",
        error.MainDirFailedCreate => "Main directory failed to create.",
        error.TaskFileFailedCreate => "Task file failed to create.",
        error.TasksDirFailedCreate => "Tasks directory failed to create.",
        error.ParsingCommandArgsFailed => "Command failed to parse arguments.",
        error.NoArgs => "No arguments passed in.",
        error.TaskNotExists => "Task does not exist.",
        error.NamespaceNotExists => "Namespace does not exist.",
        error.TaskAlreadyRunning => "Task is already running.",
        error.TaskNotRunning => "Task is not running.",
        error.MissingArgumentValue => "One or more arguments are missing its value. Run mlt help for more info.",
        error.InvalidArgument => "One or more arguments are invalid. Run mlt help for more info.",
        error.InvalidOption => "One or more options are invalid. Run mlt help for more info.",
        error.MissingArgument => "Missing option. Run mlt help for more info.",
        error.CorruptedTask => "One or more tasks are corrupted. Run `mlt health` to troubleshoot",
        error.CpuLimitValueInvalid => "Cpu limit value invalid. Must be a number in between 1 and 99.",
        error.CpuLimitValueMissing => "Cpu limit needs to have a value.",
        error.MemoryLimitValueInvalid => "Memory must have be a valid number with a suffix e.g 10(B, K, M ...).",
        error.MemoryLimitValueMissing => "Memory limit needs to have a value.",
        error.NamespaceValueMissing => "Namespace flag needs to have a value.",
        error.NamespaceValueInvalid => "Namespace flag can only have letters in its value.",
        error.NamespaceValueCantBeAll => "Namespace name cannot be 'all'.",
        else => "Unknown error occurred, code",
    };
}
